[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-cachydepths5k
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-cachydepths5k
GtkTheme=oomox-cachydepths5k
IconTheme=oomox-cachydepths5k
MetacityTheme=oomox-cachydepths5k
