[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Cachydepths5K
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Cachydepths5K
GtkTheme=oomox-Cachydepths5K
IconTheme=oomox-Cachydepths5K
MetacityTheme=oomox-Cachydepths5K
